language: node_js
addons:
  apt: 
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - gcc-multilib
script:
  - ./update_libs.sh
  - cd Bounce; npm install
  - cd Bounce; npm run-script package
after_script:
  - ls -l
