language: node_js
sudo: false

env:
  - OUTPUT_DIR=output CLOSURE_DIR=node_modules/google-closure-library

cache:
  directories:
    - node_modules

before_install: # We need jre
#  - sudo apt-get -qq update
#  - sudo apt-get install -y default-jre
  - wget -nc http://dl.google.com/closure-compiler/compiler-latest.zip
# Closure compiler.jar
  - mkdir compiler
  - unzip compiler-latest.zip -d compiler
install:
# Closure library
  - npm install google-closure-library
script:
  - mkdir output
  # Build start compressed
  - scripts/make_compressed.sh
  # Assemble files into output folder.
  - scripts/assemble_output.sh
after_script:
  - ls -l ${OUTPUT_DIR}
  - ls -l
  - ls -l node_modules
#after_success:
  # Zip up output folder

