language: node_js
node_js:
  - "6.9.1"
addons:
  apt:
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - gcc-multilib
# before_script:
#   - chmod +x update_libs.sh
script:
  # - ./update_libs.sh
  - cd Bounce
  - npm install
  - npm run-script package
after_script:
  - ls -l
  - ls -l output
# addons:
#   artifacts: true
# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true