environment:
  nodejs_version: "6"

version: '0.5.{build}'
platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: |
      Install-Product node $env:nodejs_version $PLATFORM
  # install modules
  - cmd: |
      cd Bounce
      npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  # - npm test

build_script:
  - cmd: |
      npm run-script windows-rebuild
      npm run-script package
      dir output

artifacts:
  - path: Bounce/output/Bounce-win32-x64.zip
    name: Bounce-win32-x64.zip
  - path: Bounce/output/Bounce-win32-ia32.zip
    name: Bounce-win32-ia32.zip
# deploy:
  # - provider: GitHub
  #   artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
  #   draft: false
  #   prerelease: false
  #   on:
  #     branch: master                # release from master branch only
  #     appveyor_repo_tag: true       # deploy on tag push only
