environment:
  nodejs_version: "6"

version: '0.5.{build}'
platform:
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: |
      Install-Product node $env:nodejs_version $env:platform
  # install modules
  - cmd: |
      cd Bounce
      npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  # - npm test

build_script:
  - cmd: |
      npm run-script dist
      dir output
      cd ..
      cd
      dir

artifacts:
  - path: "Bounce/output/Bounce Setup *.exe"
    name: Bounce Setup
deploy:
  - provider: GitHub
    description: Unzip the release for your system, run Bounce.exe
    artifact: Bounce-win*.zip # Upload the zip files
    draft: false
    auth_token:
        secure: CA6aBSeMTeBZ1vRWDV1FN51/tkXMg6yudu1ir3BKWAHvwN4EtcwOP3ThyDMoq+i7 # your encrypted token from GitHub
    prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
